spring:
  application:
    name: spring-vault

  config:
    import: vault://secret/person?prefix=person.

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
